import type { AboutPageData } from "@/types/about";

export const aboutPageData: AboutPageData = {
  hero: {
    title: "Brand Story",
    slogan: "Bringing Happy to everyone. Let love run wild!",
    backgroundImage: "/images/about/aura-about-banner.webp",
    backgroundAlt: "Aura brand story hero background",
    fallbackColor: "#1a1a2e",
  },

  brandMessage: {
    text: `Connect, share, and explore in 
      an open and free space.`,
  },

  stats: [
    {
      id: "country",
      value: 12,
      label: "Country",
    },
    {
      id: "global-users",
      value: 1600000,
      suffix: "+",
      label: "Global Users",
    },
  ],

  galleryCategories: [
    { id: "social-contact", label: "Social Contact", order: 1 },
    { id: "share", label: "Share", order: 2 },
    { id: "brand", label: "Brand", order: 3 },
    { id: "activity", label: "Activity", order: 4 },
  ],

  galleryPhotos: [
    // Social Contact
    {
      id: "sc-01",
      title: "My Aura stories",
      featuredImage: "/images/about/social-01.webp",
      imageAlt: "Social contact moment shared on Aura",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-02",
      title: "My Aura stories",
      featuredImage: "/images/about/social-02.webp",
      imageAlt: "Friends connecting through Aura",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-03",
      title: "My Aura stories",
      featuredImage: "/images/about/social-03.webp",
      imageAlt: "Aura community gathering",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-04",
      title: "My Aura stories",
      featuredImage: "/images/about/social-04.webp",
      imageAlt: "Sharing moments on Aura platform",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-05",
      title: "My Aura stories",
      featuredImage: "/images/about/social-05.webp",
      imageAlt: "Aura social connection experience",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-06",
      title: "My Aura stories",
      featuredImage: "/images/about/social-06.webp",
      imageAlt: "Aura community member story",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-07",
      title: "My Aura stories",
      featuredImage: "/images/about/social-07.webp",
      imageAlt: "Aura user sharing their journey",
      category: "social-contact",
      cardSize: "small",
    },
    // Share
    {
      id: "sh-01",
      title: "My Aura stories",
      featuredImage: "/images/about/share-01.webp",
      imageAlt: "Sharing creative content on Aura",
      category: "share",
      cardSize: "large",
    },
    {
      id: "sh-02",
      title: "My Aura stories",
      featuredImage: "/images/about/share-02.webp",
      imageAlt: "Aura content sharing experience",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-03",
      title: "My Aura stories",
      featuredImage: "/images/about/share-03.webp",
      imageAlt: "Community sharing moments",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-04",
      title: "My Aura stories",
      featuredImage: "/images/about/share-04.webp",
      imageAlt: "Sharing life on Aura",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-05",
      title: "My Aura stories",
      featuredImage: "/images/about/share-05.webp",
      imageAlt: "Aura sharing community",
      category: "share",
      cardSize: "large",
    },
    // Brand
    {
      id: "br-01",
      title: "My Aura stories",
      featuredImage: "/images/about/brand-01.webp",
      imageAlt: "Aura brand identity showcase",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-02",
      title: "My Aura stories",
      featuredImage: "/images/about/brand-02.webp",
      imageAlt: "Aura brand visual story",
      category: "brand",
      cardSize: "large",
    },
    {
      id: "br-03",
      title: "My Aura stories",
      featuredImage: "/images/about/brand-03.webp",
      imageAlt: "Aura brand culture",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-04",
      title: "My Aura stories",
      featuredImage: "/images/about/brand-04.webp",
      imageAlt: "Aura brand expression",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-05",
      title: "My Aura stories",
      featuredImage: "/images/about/brand-05.webp",
      imageAlt: "Aura brand community",
      category: "brand",
      cardSize: "small",
    },
    // Activity
    {
      id: "ac-01",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-01.webp",
      imageAlt: "Aura community activity highlight",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-02",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-02.webp",
      imageAlt: "Aura event participation",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-03",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-03.webp",
      imageAlt: "Aura community event",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-04",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-04.webp",
      imageAlt: "Active Aura community members",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-05",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-05.webp",
      imageAlt: "Aura activity showcase",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-06",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-06.webp",
      imageAlt: "Aura activity showcase",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-07",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-07.webp",
      imageAlt: "Aura activity showcase",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-08",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-08.webp",
      imageAlt: "Aura activity showcase",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-09",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-03.webp",
      imageAlt: "Aura community gathering",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-10",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-05.webp",
      imageAlt: "Aura team bonding",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-11",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-01.webp",
      imageAlt: "Aura outdoor activity",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-12",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-07.webp",
      imageAlt: "Aura creative workshop",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-13",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-02.webp",
      imageAlt: "Aura celebration event",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-14",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-04.webp",
      imageAlt: "Aura member spotlight",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-15",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-06.webp",
      imageAlt: "Aura seasonal event",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-16",
      title: "My Aura stories",
      featuredImage: "/images/about/aura-about-08.webp",
      imageAlt: "Aura community fun day",
      category: "activity",
      cardSize: "small",
    },
  ],

  cta: {
    heading: "You can join Aura",
    description: `Become a member of a supportive community
        that values equality and open dialogue.`,
  },

  emptyState: {
    message: "No photos available in this category yet.",
  },
};
