import type { AboutPageData } from "@/types/about";

export const aboutPageData: AboutPageData = {
  hero: {
    title: "Brand Story",
    slogan: "Bringing Happy to everyone. Let love run wild!",
    backgroundImage: "/images/about/aura-about-banner.webp",
    backgroundAlt: "Aura brand story hero background",
    fallbackColor: "#1a1a2e",
  },

  brandMessage: {
    text: `Connect, share, and explore in 
      an open and free space.`,
  },

  stats: [
    {
      id: "country",
      value: 12,
      label: "Country",
    },
    {
      id: "global-users",
      value: 1600000,
      suffix: "+",
      label: "Global Users",
    },
  ],

  galleryCategories: [
    { id: "social-contact", label: "Social Contact", order: 1 },
    { id: "share", label: "Share", order: 2 },
    { id: "brand", label: "Brand", order: 3 },
    { id: "activity", label: "Activity", order: 4 },
  ],

  galleryPhotos: [
    // Social Contact (12)
    {
      id: "sc-01",
      title: "Friday night hangout with my Aura crew",
      featuredImage: "/images/explore/aura-explore-03.webp",
      imageAlt: "Friends gathering for a Friday night hangout",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-02",
      title: "Met my best friend on Aura last year",
      featuredImage: "/images/about/aura-about-02.webp",
      imageAlt: "Two friends who met through Aura",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-03",
      title: "Sunday brunch with the group chat",
      featuredImage: "/images/explore/aura-explore-17.webp",
      imageAlt: "Group of friends at a Sunday brunch",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-04",
      title: "Voice chat that turned into a 3-hour talk",
      featuredImage: "/images/about/aura-about-06.webp",
      imageAlt: "Friends on a long voice call together",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-05",
      title: "Reunited across time zones",
      featuredImage: "/images/explore/aura-explore-09.webp",
      imageAlt: "Friends reuniting from different countries",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-06",
      title: "Our rooftop movie night, organized on Aura",
      featuredImage: "/images/about/aura-about-04.webp",
      imageAlt: "Rooftop movie night with friends",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-07",
      title: "Coffee date with a stranger who became family",
      featuredImage: "/images/explore/aura-explore-11.webp",
      imageAlt: "Two people sharing coffee and conversation",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-08",
      title: "Game night with friends I met online",
      featuredImage: "/images/explore/aura-explore-01.webp",
      imageAlt: "Friends playing games together at home",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-09",
      title: "Surprise birthday party we planned on Aura",
      featuredImage: "/images/about/aura-about-08.webp",
      imageAlt: "Surprise birthday celebration with friends",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-10",
      title: "Road trip crew, assembled in one group chat",
      featuredImage: "/images/explore/aura-explore-15.webp",
      imageAlt: "Friends on a road trip adventure",
      category: "social-contact",
      cardSize: "small",
    },
    {
      id: "sc-11",
      title: "Late-night bonfire with the whole squad",
      featuredImage: "/images/explore/aura-explore-06.webp",
      imageAlt: "Friends around a bonfire at night",
      category: "social-contact",
      cardSize: "large",
    },
    {
      id: "sc-12",
      title: "From strangers to soulmates in 6 months",
      featuredImage: "/images/about/aura-about-01.webp",
      imageAlt: "Close friends sharing a heartfelt moment",
      category: "social-contact",
      cardSize: "small",
    },
    // Share (11)
    {
      id: "sh-01",
      title: "Shared my first painting and got so much love",
      featuredImage: "/images/explore/aura-explore-14.webp",
      imageAlt: "User sharing their painting with the community",
      category: "share",
      cardSize: "large",
    },
    {
      id: "sh-02",
      title: "Posted my travel photos from Bali",
      featuredImage: "/images/about/aura-about-03.webp",
      imageAlt: "Travel photos from Bali shared on Aura",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-03",
      title: "Cooking my grandma's recipe for everyone",
      featuredImage: "/images/explore/aura-explore-07.webp",
      imageAlt: "Home-cooked meal shared with the community",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-04",
      title: "My street photography collection",
      featuredImage: "/images/about/aura-about-05.webp",
      imageAlt: "Street photography collection by an Aura user",
      category: "share",
      cardSize: "large",
    },
    {
      id: "sh-05",
      title: "Shared my original song and it went viral",
      featuredImage: "/images/explore/aura-explore-19.webp",
      imageAlt: "Musician sharing original music on Aura",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-06",
      title: "DIY room makeover — before and after",
      featuredImage: "/images/explore/aura-explore-02.webp",
      imageAlt: "Room makeover transformation photos",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-07",
      title: "My cat's daily adventures, episode 47",
      featuredImage: "/images/about/aura-about-07.webp",
      imageAlt: "Adorable cat photos shared by a community member",
      category: "share",
      cardSize: "large",
    },
    {
      id: "sh-08",
      title: "Sunset timelapse from my balcony",
      featuredImage: "/images/explore/aura-explore-10.webp",
      imageAlt: "Beautiful sunset timelapse photography",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-09",
      title: "First time surfing — I actually stood up!",
      featuredImage: "/images/explore/aura-explore-16.webp",
      imageAlt: "User surfing for the first time",
      category: "share",
      cardSize: "small",
    },
    {
      id: "sh-10",
      title: "Handmade pottery collection from my weekend class",
      featuredImage: "/images/explore/aura-explore-04.webp",
      imageAlt: "Handmade pottery pieces displayed together",
      category: "share",
      cardSize: "large",
    },
    {
      id: "sh-11",
      title: "My journal sketches from a month in Tokyo",
      featuredImage: "/images/about/aura-about-01.webp",
      imageAlt: "Travel journal sketches from Tokyo",
      category: "share",
      cardSize: "small",
    },
    // Brand (10)
    {
      id: "br-01",
      title: "Behind the scenes of our new logo",
      featuredImage: "/images/explore/aura-explore-08.webp",
      imageAlt: "Behind the scenes of Aura logo design process",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-02",
      title: "The story behind Aura's signature colors",
      featuredImage: "/images/about/aura-about-06.webp",
      imageAlt: "Aura brand color palette inspiration",
      category: "brand",
      cardSize: "large",
    },
    {
      id: "br-03",
      title: "Our Jakarta pop-up store experience",
      featuredImage: "/images/explore/aura-explore-18.webp",
      imageAlt: "Aura pop-up store in Jakarta",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-04",
      title: "Designing merch the community actually wants",
      featuredImage: "/images/about/aura-about-02.webp",
      imageAlt: "Aura community merchandise design session",
      category: "brand",
      cardSize: "large",
    },
    {
      id: "br-05",
      title: "Aura x local artists collaboration wall",
      featuredImage: "/images/explore/aura-explore-12.webp",
      imageAlt: "Mural created by local artists for Aura",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-06",
      title: "How we built the Aura mascot from scratch",
      featuredImage: "/images/explore/aura-explore-05.webp",
      imageAlt: "Aura mascot design and creation process",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-07",
      title: "Our first billboard went live in Manila",
      featuredImage: "/images/about/aura-about-04.webp",
      imageAlt: "Aura billboard advertisement in Manila",
      category: "brand",
      cardSize: "large",
    },
    {
      id: "br-08",
      title: "Aura brand film — 60 seconds of pure joy",
      featuredImage: "/images/explore/aura-explore-13.webp",
      imageAlt: "Still frame from Aura brand film",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-09",
      title: "Team photoshoot at our new office",
      featuredImage: "/images/about/aura-about-08.webp",
      imageAlt: "Aura team at the new office",
      category: "brand",
      cardSize: "small",
    },
    {
      id: "br-10",
      title: "Packaging design for Aura gift boxes",
      featuredImage: "/images/explore/aura-explore-01.webp",
      imageAlt: "Aura gift box packaging design showcase",
      category: "brand",
      cardSize: "large",
    },
    // Activity (16)
    {
      id: "ac-01",
      title: "Beach cleanup day with 200+ volunteers",
      featuredImage: "/images/explore/aura-explore-18.webp",
      imageAlt: "Volunteers at a beach cleanup event organized by Aura",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-02",
      title: "Aura Music Fest 2025 highlights",
      featuredImage: "/images/explore/aura-explore-19.webp",
      imageAlt: "Crowd enjoying live music at Aura Music Fest",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-03",
      title: "Marathon runners powered by Aura community",
      featuredImage: "/images/about/aura-about-03.webp",
      imageAlt: "Runners at a community marathon event",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-04",
      title: "Weekend hiking trip to Mount Bromo",
      featuredImage: "/images/explore/aura-explore-02.webp",
      imageAlt: "Hikers at the summit of Mount Bromo",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-05",
      title: "Dance workshop led by our community members",
      featuredImage: "/images/about/aura-about-05.webp",
      imageAlt: "Community members at a dance workshop",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-06",
      title: "Charity gala night — we raised $50K together",
      featuredImage: "/images/explore/aura-explore-04.webp",
      imageAlt: "Aura charity gala event night",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-07",
      title: "Open mic night at the Aura Lounge",
      featuredImage: "/images/about/aura-about-07.webp",
      imageAlt: "Performer at open mic night in Aura Lounge",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-08",
      title: "Yoga sunrise session by the lake",
      featuredImage: "/images/explore/aura-explore-06.webp",
      imageAlt: "Group yoga session at sunrise by the lake",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-09",
      title: "Art jam session — everyone's a creator here",
      featuredImage: "/images/about/aura-about-01.webp",
      imageAlt: "Community art jam session with painting and drawing",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-10",
      title: "Night market food tour with 50 foodies",
      featuredImage: "/images/explore/aura-explore-08.webp",
      imageAlt: "Group exploring a night market food tour",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-11",
      title: "Skateboarding meetup at the park",
      featuredImage: "/images/explore/aura-explore-09.webp",
      imageAlt: "Skateboarders at a community meetup in the park",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-12",
      title: "Photography walk through old town",
      featuredImage: "/images/explore/aura-explore-10.webp",
      imageAlt: "Photographers exploring old town streets together",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-13",
      title: "New Year countdown party 2026",
      featuredImage: "/images/about/aura-about-02.webp",
      imageAlt: "New Year celebration party with Aura community",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-14",
      title: "Volunteering at the local children's home",
      featuredImage: "/images/explore/aura-explore-12.webp",
      imageAlt: "Volunteers spending time at a children's home",
      category: "activity",
      cardSize: "small",
    },
    {
      id: "ac-15",
      title: "Summer pool party — best day ever",
      featuredImage: "/images/explore/aura-explore-13.webp",
      imageAlt: "Aura community summer pool party",
      category: "activity",
      cardSize: "large",
    },
    {
      id: "ac-16",
      title: "Board game night that lasted until 3 AM",
      featuredImage: "/images/about/aura-about-04.webp",
      imageAlt: "Friends playing board games late into the night",
      category: "activity",
      cardSize: "small",
    },
  ],

  cta: {
    heading: "You can join Aura",
    description: `Become a member of a supportive community
        that values equality and open dialogue.`,
  },

  emptyState: {
    message: "No photos available in this category yet.",
  },
};
