import type { ExplorePageData } from "@/types/explore";

export const explorePageData: ExplorePageData = {
  hero: {
    title: "Community Story",
    subtitle: "Connect, share, and explore in a space free from judgment",
    description: `Aura is committed to growing alongside its users, providing each user with more precise andpersonalized services, and continuously optimizing and upgrading itself based on user feed--back.With a user-centric approach, Aura expands its platform boundaries through communi-ty, exploring the infinite possibilities brought by technology, and bringing a more refined andenjoyable experience to people's lives.`,
    backgroundImage: "/images/05Explore/Aura_Explore_Banner-01.webp",
    backgroundAlt: "Aura community hero background with warm sunset silhouette",
    fallbackColor: "#1a1a2e",
  },

  galleryPhotos: [
    {
      id: "explore-01",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-01.webp",
      imageAlt: "Aura community moment captured",
      cardSize: "large",
      order: 1,
    },
    {
      id: "explore-02",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-02.webp",
      imageAlt: "Sharing life on Aura platform",
      cardSize: "small",
      order: 2,
    },
    {
      id: "explore-03",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-03.webp",
      imageAlt: "Aura community connection",
      cardSize: "small",
      order: 3,
    },
    {
      id: "explore-04",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-04.webp",
      imageAlt: "Aura lifestyle moment",
      cardSize: "large",
      order: 4,
    },
    {
      id: "explore-05",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-05.webp",
      imageAlt: "Exploring together on Aura",
      cardSize: "small",
      order: 5,
    },
    {
      id: "explore-06",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-06.webp",
      imageAlt: "Aura community adventure",
      cardSize: "small",
      order: 6,
    },
    {
      id: "explore-07",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-07.webp",
      imageAlt: "Aura members sharing stories",
      cardSize: "small",
      order: 7,
    },
    {
      id: "explore-08",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-08.webp",
      imageAlt: "Authentic Aura experience",
      cardSize: "large",
      order: 8,
    },
    {
      id: "explore-09",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-09.webp",
      imageAlt: "Aura community gathering",
      cardSize: "small",
      order: 9,
    },
    {
      id: "explore-10",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-10.webp",
      imageAlt: "Aura connection moment",
      cardSize: "small",
      order: 10,
    },
    {
      id: "explore-11",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-11.webp",
      imageAlt: "Aura community celebration",
      cardSize: "large",
      order: 11,
    },
    {
      id: "explore-12",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-12.webp",
      imageAlt: "Aura community discovery",
      cardSize: "small",
      order: 12,
    },
    {
      id: "explore-13",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-13.webp",
      imageAlt: "Aura creative expression",
      cardSize: "small",
      order: 13,
    },
    {
      id: "explore-14",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-14.webp",
      imageAlt: "Aura authentic living",
      cardSize: "large",
      order: 14,
    },
    {
      id: "explore-15",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-15.webp",
      imageAlt: "Aura shared experiences",
      cardSize: "small",
      order: 15,
    },
    {
      id: "explore-16",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-16.webp",
      imageAlt: "Aura everyday inspiration",
      cardSize: "small",
      order: 16,
    },
    {
      id: "explore-17",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-17.webp",
      imageAlt: "Aura community vibes",
      cardSize: "large",
      order: 17,
    },
    {
      id: "explore-18",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-18.webp",
      imageAlt: "Aura meaningful connections",
      cardSize: "small",
      order: 18,
    },
    {
      id: "explore-19",
      title: "My Aura stories",
      featuredImage: "/images/05Explore/Aura_Explore-19.webp",
      imageAlt: "Aura life moments",
      cardSize: "small",
      order: 19,
    },
  ],

  emptyState: {
    message: "Stories coming soon",
  },
};
